# cloud-init.yaml

# Set the hostname
hostname: kubernetes_UbuntuLTS

# Add user
users:
  - name: vivek
    passwd: password
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ssh-rsa "key" vivek@maindt-vivek

# Update and upgrade packages
package_upgrade: true

# Install additional packages
packages:
  - git
  - curl
  - ufw  # Install Uncomplicated Firewall
  - openssh-client
  - openssh-server

# Run commands after package installation
runcmd:
  - echo "TEST TEST TEST"
  - echo "TEST TEST TEST"
  - [ sudo, ufw, allow, ssh ]
  - [ sudo, ufw, allow, 22 ]
  - [ sudo, ufw, enable ]

# Reboot after all cloud-init tasks are done
power_state:
  mode: reboot

# Add custom files
write_files:
  - path: /etc/motd
    content: |
      TEST TEST TEST.

# Run additional commands at first boot
bootcmd:
  - echo "Running commands at first boot!"

# Set the timezone
timezone: America/New_York
